### ISSUE TITLE
failed to compile on centos 6.5

### ISSUE THREAD

**Issue by ericx10ng** [mozilla-services/heka#1761]
Hello,

an error happened when I compiled heka(master) on centos 6.5.

[ 77%] Performing build step for 'lua_sax'
Scanning dependencies of target sts_test
[ 25%] Building C object src/CMakeFiles/sts_test.dir/symtseries.c.o
cc1: warnings being treated as errors
/vagrant/heka/build/ep_base/Build/lua_sandbox/ep_base/Source/lua_sax/src/symtseries.c: In function ‘online_mu_sigma_random_test’:
/vagrant/heka/build/ep_base/Build/lua_sandbox/ep_base/Source/lua_sax/src/symtseries.c:766: error: ‘win’ may be used uninitialized in this function
make[8]: *** [src/CMakeFiles/sts_test.dir/symtseries.c.o] Error 1
make[7]: *** [src/CMakeFiles/sts_test.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [ep_base/Stamp/lua_sax/lua_sax-build] Error 2
make[4]: *** [CMakeFiles/lua_sax.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ep_base/Stamp/lua_sandbox/lua_sandbox-build] Error 2
make[1]: *** [CMakeFiles/lua_sandbox.dir/all] Error 2
make: *** [all] Error 2

**Comment by tianchaijz** [comment]
I got this error in CentOS 6.5 too.

**Comment by trink** [comment]
The warning appears to be bogus but it can be corrected.  Just out of curiosity what compiler/version are you using?

**Comment by tianchaijz** [comment]
@trink my gcc version info:
```
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
```

**Comment by trink** [comment]
@tianchaijz will you try out the branch above, thanks

**Comment by tianchaijz** [comment]
That works, thanks @trink !

**Comment by sathieu** [comment]
this can be closed then.
